# 

In [4]:
using LinearAlgebra
using Plots
using Plotly
using SymPy

plotly()

Plots.PlotlyBackend()

In [5]:
# Ellipses, Part 1: Finding Eigen (Spectral) Decomposition:

P = [1.5 -0.5; -0.5 1.5]
x_c = [0; 0]

λ, U = eigen(P)

Eigen{Float64,Float64,Array{Float64,2},Array{Float64,1}}
values:
2-element Array{Float64,1}:
 1.0
 2.0
vectors:
2×2 Array{Float64,2}:
 -0.707107  -0.707107
 -0.707107   0.707107

In [6]:
# Showing that the eigen equality holds for each vector.
println("Equality for first vector: ", P*U[1,:] == λ[1]*U[1,:])
println("Equality for second vector: ", P*U[2,:] == λ[2]*U[2,:])

Equality for first vector: true
Equality for second vector: true


In [7]:
# Forming our Lambda matrix
Λ = zeros(2,2)
Λ[1,1] = λ[1]
Λ[2,2] = λ[2]
Λ

2×2 Array{Float64,2}:
 1.0  0.0
 0.0  2.0

In [8]:
c = 1 # constant that our quadratic is limited by:

1

In [9]:
x = Sym("x")
ex = sqrt(λ[2]-(λ[2]x^2)/λ[1])
ex_2 = -1*sqrt(λ[2]-(λ[2]x^2)/λ[1])

xs = collect(-1:0.05:1)

ys1 = ex(xs)

Plots.plot(ex)        # plot of a symbolic expression
Plots.plot!(ex_2)
Plots.title!("x̃ Space")

<!DOCTYPE html>
 
 
 Plots.jl

In [14]:
ys1 = zeros(length(xs))

for i = 1:length(ys1)
    ys1[i] = ex(x=>xs[i])
end

ys2 = zeros(length(xs))

for i = 1:length(ys2)
    ys2[i] = ex_2(x=>xs[i])
end

In [15]:
Plots.plot(xs, ys1)
Plots.plot!(xs, ys2)
Plots.title!("Still in squiggle X space!")

<!DOCTYPE html>
 
 
 Plots.jl

In [16]:
comb_mat_1 = [transpose(xs); transpose(ys1)]
comb_mat_2 = [transpose(xs); transpose(ys2)]

2×41 Array{Float64,2}:
 -1.0  -0.95      -0.9       -0.85      …   0.9        0.95      1.0
  0.0  -0.441588  -0.616441  -0.744983     -0.616441  -0.441588  0.0

In [17]:
trans_comb_mat_1 = U*comb_mat_1
trans_comb_mat_2 = U*comb_mat_2

2×41 Array{Float64,2}:
 0.707107  0.984001  1.07229   1.12782    …  -0.200506  -0.359502  -0.707107
 0.707107  0.359502  0.200506  0.0742581     -1.07229   -0.984001  -0.707107

In [18]:
Plots.plot(trans_comb_mat_1[1,:], trans_comb_mat_1[2,:])
Plots.plot!(trans_comb_mat_2[1,:], trans_comb_mat_2[2,:])
Plots.title!("Transformed using U")

<!DOCTYPE html>
 
 
 Plots.jl

In [19]:
println("Next: just translate back using x_0")

Next: just translate back using x_0
